use_frameworks!

platform :ios, '12.0'

target 'DBEnginer_Example' do
  pod 'DBEnginer', :path => '../'
  pod 'Unrealm', '~> 1.9.5'
  target 'DBEnginer_Tests' do
    inherit! :search_paths

    
  end
end
