use_frameworks!

platform :ios, '12.0'

target 'DBEnginer_Example' do
  pod 'DBEnginer', :path => '../'
  pod 'Unrealm', '~> 1.9.5'
  target 'DBEnginer_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Do either this:
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      # or this:
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
